# detail
GAME_DETAIL_GENRE_SIZE = (10, 1)
GAME_DETAIL_TEXT_SIZE = (50, 1)
GAME_DETAIL_BUTTON_SIZE = (30, 1)
GAME_DETAIL_SITE_SIZE = (60, 1)
# add_menu
GAME_MENU_GENRE_SIZE = (10, 2)
GAME_MENU_BROWSE_SIZE = (67, 1)
GAME_MENU_BUTTON_SIZE = (32, 1)
GAME_MENU_TEXT_GENRE_SIZE = (57, 1)
GAME_MENU_TEXT_INPUT_SIZE = (58, 2)
GAME_MENU_SITE_SIZE = (68, 1)
