FONT_SIZE = [0, 20]
ICON_SIZE = (50, 50)
GENRE_NAME_DATA_NUMBER = 1
DATE_BIRTH_DATA_NUMBER = 2
COMPANY_NAME_DATA_NUMBER = 3
IMAGE_DATA_NUMBER = 5
SITE_DATA_NUMBER = 6
EXEC_DATA_NUMBER = 7
HARD_DATA_NUMBER = 8
NUMBER_DATA_PER = 10
ONE_COLUMN_LENGTH = 10
TITLE = "Spielliste v1.1.0"
# game.py
# detail
GAME_DETAIL_GENRE_SIZE = (10, 1)
GAME_DETAIL_TEXT_SIZE = (50, 1)
GAME_DETAIL_BUTTON_SIZE = (30, 1)
GAME_DETAIL_SITE_SIZE = (60, 1)
# add_menu
GAME_MENU_GENRE_SIZE = (10, 2)
# menu.py
